export enum SocketEvents {
    Connect = "connect",
    Disconnect = "disconnect",
    ReservationsUpdated = "reservations/update",
    LogoutSockets = "logout-socket",
    Authorize = "authorize",
    EmailsUpdated = "emails/update",
    SubscriptionsUpdated = "subscriptions/update",
    MassFreezeUpdated = "mass-features/freeze-update",
    MassFreezeError = "mass-features/freeze-error",
    InstructorProfileUpdated = "instructor/profile-updated",
    SubscriptionFreezeStatusUpdated = "subscriptions/freeze-status-update",
    NewNotification = "notifications/new-notification",
    CustomerNotes = "customer/notes",
    GymSettingUpdate = "gym/settings-update",
    SalesUpdated = "sales/update",
    TwilioRoomCreated = "twilio/room-created",
    VideoConferenceEnd = "twilio/room-completed",
    TwilioInstructorConnected = "twilio/instructor-connected"
}